# Testcase Structure:
#    name: String, // The name of the testcase
#    subname: Option<String>, // used for unittests later
#    testcase_type: String, //Only IO supported now
#    description: Option<String>, // optional description
#    args: Option<String>, // command line arguments 
#    cflags: Option<String>, // compile flags
#    tags: Option<Tags>, // tags for unit tests
#    in_file: Option<String>, // stdin file 
#    exp_file: Option<String>, // stdout file
#    in_string: Option<String>, // stdin string (in_file has higher priority)
#    exp_string: Option<String>, // stdout string (out_file has higher priority)
#    exp_retvar: Option<i32>, // optional expected status code
#    timeout: Option<i32>, // timeout in seconds .. default is 5 sec
#    env_vars:Option<String>, // optional environment parameters RAND_SEED=123,foo=bar

[project_definition]
project_name = "main"
makefile_path = "."
maketarget = "all"

[[testcases]]
name = "Starkes Untergewicht"
testcase_type = "IO"
in_file = "tests/01/in"
exp_file = "tests/01/out"
exp_retvar = 0

[[testcases]]
name = "Mäßiges Untergewicht"
testcase_type = "IO"
in_file = "tests/02/in"
exp_file = "tests/02/out"
exp_retvar = 0

[[testcases]]
name = "Leichtes Untergewicht"
testcase_type = "IO"
in_file = "tests/03/in"
exp_file = "tests/03/out"
exp_retvar = 0

[[testcases]]
name = "Normalgewicht"
testcase_type = "IO"
in_file = "tests/04/in"
exp_file = "tests/04/out"
exp_retvar = 0

[[testcases]]
name = "Präadipositas"
testcase_type = "IO"
in_file = "tests/05/in"
exp_file = "tests/05/out"
exp_retvar = 0

[[testcases]]
name = "Adipositas Grad I"
testcase_type = "IO"
in_file = "tests/06/in"
exp_file = "tests/06/out"
exp_retvar = 0

[[testcases]]
name = "Adipositas Grad II"
testcase_type = "IO"
in_file = "tests/07/in"
exp_file = "tests/07/out"
exp_retvar = 0

[[testcases]]
name = "Adipositas Grad III"
testcase_type = "IO"
in_file = "tests/08/in"
exp_file = "tests/08/out"
exp_retvar = 0
