/* Generated by Yosys 0.46 (git sha1 e97731b9d, clang++ 16.0.0 -fPIC -O3) */

(* hdlname = "fulladder" *)
(* src = "src/fulladder.v:1.1-15.10" *)
module fulladder(a_i, b_i, c_i, sum_o, c_o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "src/fulladder.v:8.13-8.16" *)
  input a_i;
  wire a_i;
  (* src = "src/fulladder.v:9.13-9.16" *)
  input b_i;
  wire b_i;
  (* src = "src/fulladder.v:10.13-10.16" *)
  input c_i;
  wire c_i;
  (* src = "src/fulladder.v:12.14-12.17" *)
  output c_o;
  wire c_o;
  (* src = "src/fulladder.v:11.14-11.19" *)
  output sum_o;
  wire sum_o;
  assign _02_ = b_i ^ a_i;
  assign sum_o = _02_ ^ c_i;
  assign _03_ = b_i & a_i;
  assign _04_ = c_i & b_i;
  assign _00_ = _04_ | _03_;
  assign _01_ = c_i & a_i;
  assign c_o = _01_ | _00_;
endmodule
