/*

 * Generated by Digital. Don't modify this file!

 * Any changes will be lost if this file is regenerated.

 */

module fulladder (
input A,
input B,
input C,
output logic Y,
output logic X
);

assign Y = ((~ A & ~ B & C) | (~ A & B & ~ C) | (A & ~ B & ~ C) | (A & B & C));
assign X = ((A & C) | (A & B) | (B & C));
endmodule

