/* Generated by Yosys 0.46 (git sha1 e97731b9d, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "calculator.sv:1.1-96.10" *)
module calculator(clk_i, rst_i, a_i, b_i, input_valid_i, calc_i, mode_i, clear_i, result_o, output_valid_o);
  (* src = "calculator.sv:63.5-92.8" *)
  wire [4:0] _000_;
  (* src = "calculator.sv:63.5-92.8" *)
  wire [4:0] _001_;
  (* src = "calculator.sv:63.5-92.8" *)
  wire [1:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  (* src = "fulladder.sv:13.21-13.30" *)
  wire _016_;
  (* src = "fulladder.sv:13.35-13.44" *)
  wire _017_;
  (* src = "fulladder.sv:13.49-13.58" *)
  wire _018_;
  (* src = "fulladder.sv:13.20-13.45" *)
  wire _019_;
  (* src = "fulladder.sv:12.20-12.29" *)
  wire _020_;
  (* src = "fulladder.sv:13.21-13.30" *)
  wire _021_;
  (* src = "fulladder.sv:13.35-13.44" *)
  wire _022_;
  (* src = "fulladder.sv:13.49-13.58" *)
  wire _023_;
  (* src = "fulladder.sv:13.20-13.45" *)
  wire _024_;
  (* src = "fulladder.sv:12.20-12.29" *)
  wire _025_;
  (* src = "fulladder.sv:13.21-13.30" *)
  wire _026_;
  (* src = "fulladder.sv:13.35-13.44" *)
  wire _027_;
  (* src = "fulladder.sv:13.49-13.58" *)
  wire _028_;
  (* src = "fulladder.sv:13.20-13.45" *)
  wire _029_;
  (* src = "fulladder.sv:12.20-12.29" *)
  wire _030_;
  (* src = "fulladder.sv:13.21-13.30" *)
  wire _031_;
  (* src = "fulladder.sv:13.35-13.44" *)
  wire _032_;
  (* src = "fulladder.sv:13.49-13.58" *)
  wire _033_;
  (* src = "fulladder.sv:13.20-13.45" *)
  wire _034_;
  (* src = "fulladder.sv:12.20-12.29" *)
  wire _035_;
  (* src = "fulladder.sv:12.20-12.29" *)
  wire _036_;
  wire [4:0] _037_;
  wire [4:0] _038_;
  wire [4:0] _039_;
  wire [4:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:572.28-572.29" *)
  wire [5:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [5:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [2:0] _043_;
  (* force_downto = 32'd1 *)
  (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire [1:0] _044_;
  (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _045_;
  (* src = "calculator.sv:5.24-5.27" *)
  input [4:0] a_i;
  wire [4:0] a_i;
  (* hdlname = "addsub_inst FA_CHAIN[0].FA a_i" *)
  (* src = "fulladder.sv:2.18-2.21" *)
  wire \addsub_inst.FA_CHAIN[0].FA.a_i ;
  (* hdlname = "addsub_inst FA_CHAIN[0].FA b_i" *)
  (* src = "fulladder.sv:3.18-3.21" *)
  wire \addsub_inst.FA_CHAIN[0].FA.b_i ;
  (* hdlname = "addsub_inst FA_CHAIN[0].FA c_i" *)
  (* src = "fulladder.sv:4.18-4.21" *)
  wire \addsub_inst.FA_CHAIN[0].FA.c_i ;
  (* hdlname = "addsub_inst FA_CHAIN[0].FA c_o" *)
  (* src = "fulladder.sv:7.18-7.21" *)
  wire \addsub_inst.FA_CHAIN[0].FA.c_o ;
  (* hdlname = "addsub_inst FA_CHAIN[0].FA sum_o" *)
  (* src = "fulladder.sv:6.18-6.23" *)
  wire \addsub_inst.FA_CHAIN[0].FA.sum_o ;
  (* hdlname = "addsub_inst FA_CHAIN[1].FA a_i" *)
  (* src = "fulladder.sv:2.18-2.21" *)
  wire \addsub_inst.FA_CHAIN[1].FA.a_i ;
  (* hdlname = "addsub_inst FA_CHAIN[1].FA b_i" *)
  (* src = "fulladder.sv:3.18-3.21" *)
  wire \addsub_inst.FA_CHAIN[1].FA.b_i ;
  (* hdlname = "addsub_inst FA_CHAIN[1].FA c_i" *)
  (* src = "fulladder.sv:4.18-4.21" *)
  wire \addsub_inst.FA_CHAIN[1].FA.c_i ;
  (* hdlname = "addsub_inst FA_CHAIN[1].FA c_o" *)
  (* src = "fulladder.sv:7.18-7.21" *)
  wire \addsub_inst.FA_CHAIN[1].FA.c_o ;
  (* hdlname = "addsub_inst FA_CHAIN[1].FA sum_o" *)
  (* src = "fulladder.sv:6.18-6.23" *)
  wire \addsub_inst.FA_CHAIN[1].FA.sum_o ;
  (* hdlname = "addsub_inst FA_CHAIN[2].FA a_i" *)
  (* src = "fulladder.sv:2.18-2.21" *)
  wire \addsub_inst.FA_CHAIN[2].FA.a_i ;
  (* hdlname = "addsub_inst FA_CHAIN[2].FA b_i" *)
  (* src = "fulladder.sv:3.18-3.21" *)
  wire \addsub_inst.FA_CHAIN[2].FA.b_i ;
  (* hdlname = "addsub_inst FA_CHAIN[2].FA c_i" *)
  (* src = "fulladder.sv:4.18-4.21" *)
  wire \addsub_inst.FA_CHAIN[2].FA.c_i ;
  (* hdlname = "addsub_inst FA_CHAIN[2].FA c_o" *)
  (* src = "fulladder.sv:7.18-7.21" *)
  wire \addsub_inst.FA_CHAIN[2].FA.c_o ;
  (* hdlname = "addsub_inst FA_CHAIN[2].FA sum_o" *)
  (* src = "fulladder.sv:6.18-6.23" *)
  wire \addsub_inst.FA_CHAIN[2].FA.sum_o ;
  (* hdlname = "addsub_inst FA_CHAIN[3].FA a_i" *)
  (* src = "fulladder.sv:2.18-2.21" *)
  wire \addsub_inst.FA_CHAIN[3].FA.a_i ;
  (* hdlname = "addsub_inst FA_CHAIN[3].FA b_i" *)
  (* src = "fulladder.sv:3.18-3.21" *)
  wire \addsub_inst.FA_CHAIN[3].FA.b_i ;
  (* hdlname = "addsub_inst FA_CHAIN[3].FA c_i" *)
  (* src = "fulladder.sv:4.18-4.21" *)
  wire \addsub_inst.FA_CHAIN[3].FA.c_i ;
  (* hdlname = "addsub_inst FA_CHAIN[3].FA c_o" *)
  (* src = "fulladder.sv:7.18-7.21" *)
  wire \addsub_inst.FA_CHAIN[3].FA.c_o ;
  (* hdlname = "addsub_inst FA_CHAIN[3].FA sum_o" *)
  (* src = "fulladder.sv:6.18-6.23" *)
  wire \addsub_inst.FA_CHAIN[3].FA.sum_o ;
  (* hdlname = "addsub_inst FA_CHAIN[4].FA a_i" *)
  (* src = "fulladder.sv:2.18-2.21" *)
  wire \addsub_inst.FA_CHAIN[4].FA.a_i ;
  (* hdlname = "addsub_inst FA_CHAIN[4].FA b_i" *)
  (* src = "fulladder.sv:3.18-3.21" *)
  wire \addsub_inst.FA_CHAIN[4].FA.b_i ;
  (* hdlname = "addsub_inst FA_CHAIN[4].FA c_i" *)
  (* src = "fulladder.sv:4.18-4.21" *)
  wire \addsub_inst.FA_CHAIN[4].FA.c_i ;
  (* hdlname = "addsub_inst FA_CHAIN[4].FA sum_o" *)
  (* src = "fulladder.sv:6.18-6.23" *)
  wire \addsub_inst.FA_CHAIN[4].FA.sum_o ;
  (* hdlname = "addsub_inst a_i" *)
  (* src = "addsub.sv:2.23-2.26" *)
  wire [4:0] \addsub_inst.a_i ;
  (* hdlname = "addsub_inst b_i" *)
  (* src = "addsub.sv:3.23-3.26" *)
  wire [4:0] \addsub_inst.b_i ;
  (* hdlname = "addsub_inst b_mux" *)
  (* src = "addsub.sv:10.17-10.22" *)
  wire [4:0] \addsub_inst.b_mux ;
  (* hdlname = "addsub_inst c" *)
  (* src = "addsub.sv:11.17-11.18" *)
  (* unused_bits = "5" *)
  wire [5:0] \addsub_inst.c ;
  (* hdlname = "addsub_inst mode_i" *)
  (* src = "addsub.sv:4.23-4.29" *)
  wire \addsub_inst.mode_i ;
  (* hdlname = "addsub_inst result_o" *)
  (* src = "addsub.sv:6.24-6.32" *)
  wire [4:0] \addsub_inst.result_o ;
  (* src = "calculator.sv:6.24-6.27" *)
  input [4:0] b_i;
  wire [4:0] b_i;
  (* src = "calculator.sv:8.24-8.30" *)
  input calc_i;
  wire calc_i;
  (* src = "calculator.sv:10.24-10.31" *)
  input clear_i;
  wire clear_i;
  (* src = "calculator.sv:2.24-2.29" *)
  input clk_i;
  wire clk_i;
  (* src = "calculator.sv:7.24-7.37" *)
  input input_valid_i;
  wire input_valid_i;
  (* src = "calculator.sv:9.24-9.30" *)
  input mode_i;
  wire mode_i;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\LOAD_A" *)
  (* enum_value_01 = "\\LOAD_B" *)
  (* enum_value_10 = "\\CALC" *)
  (* src = "calculator.sv:24.20-24.30" *)
  (* wiretype = "\\state_t" *)
  wire [1:0] next_state;
  (* src = "calculator.sv:13.24-13.38" *)
  output output_valid_o;
  wire output_valid_o;
  (* src = "calculator.sv:27.17-27.22" *)
  reg [4:0] reg_a;
  (* src = "calculator.sv:27.24-27.29" *)
  reg [4:0] reg_b;
  (* src = "calculator.sv:12.24-12.32" *)
  output [4:0] result_o;
  wire [4:0] result_o;
  (* src = "calculator.sv:3.24-3.29" *)
  input rst_i;
  wire rst_i;
  (* enum_type = "$enum0" *)
  (* enum_value_00 = "\\LOAD_A" *)
  (* enum_value_01 = "\\LOAD_B" *)
  (* enum_value_10 = "\\CALC" *)
  (* src = "calculator.sv:24.13-24.18" *)
  (* wiretype = "\\state_t" *)
  reg [1:0] state;
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_b[0] <= 1'h0;
    else if (_007_) reg_b[0] <= _001_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_b[1] <= 1'h0;
    else if (_007_) reg_b[1] <= _001_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_b[2] <= 1'h0;
    else if (_007_) reg_b[2] <= _001_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_b[3] <= 1'h0;
    else if (_007_) reg_b[3] <= _001_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_b[4] <= 1'h0;
    else if (_007_) reg_b[4] <= _001_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) state[0] <= 1'h0;
    else state[0] <= _002_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) state[1] <= 1'h0;
    else state[1] <= _002_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_a[0] <= 1'h0;
    else if (_008_) reg_a[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_a[1] <= 1'h0;
    else if (_008_) reg_a[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_a[2] <= 1'h0;
    else if (_008_) reg_a[2] <= _000_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_a[3] <= 1'h0;
    else if (_008_) reg_a[3] <= _000_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "calculator.sv:63.5-92.8" *)
  always @(posedge clk_i, posedge rst_i)
    if (rst_i) reg_a[4] <= 1'h0;
    else if (_008_) reg_a[4] <= _000_[4];
  assign _009_ = ~state[0];
  assign _010_ = ~state[1];
  assign _006_ = clear_i |(* src = {0{1'b0}} *)  _043_[2];
  assign _008_ = _006_ &(* src = {0{1'b0}} *)  _005_;
  assign _004_ = clear_i |(* src = {0{1'b0}} *)  _043_[1];
  assign _007_ = _004_ &(* src = {0{1'b0}} *)  _003_;
  assign _005_ = _013_ |(* src = {0{1'b0}} *)  _011_;
  assign _013_ = input_valid_i |(* src = {0{1'b0}} *)  clear_i;
  assign _003_ = _013_ |(* src = {0{1'b0}} *)  _012_;
  assign _015_ = state[0] |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *)  _010_;
  assign _012_ = _009_ |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *)  state[1];
  assign _044_[1] = _042_[1] |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:594.20-594.31" *)  _042_[3];
  assign _044_[0] = _042_[2] |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:594.20-594.31" *)  _042_[4];
  assign _014_ = output_valid_o |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:598.13-598.15" *)  _043_[1];
  assign _045_ = _014_ |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:598.13-598.15" *)  _043_[2];
  assign _011_ = state[0] |(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *)  state[1];
  assign output_valid_o = ~(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *) _015_;
  assign _043_[1] = ~(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *) _012_;
  assign _043_[2] = ~(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16" *) _011_;
  assign _002_[0] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : next_state[0];
  assign _002_[1] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : next_state[1];
  assign _037_[0] = input_valid_i ? (* src = "calculator.sv:82.29-82.42|calculator.sv:82.25-83.42" *) b_i[0] : 1'hx;
  assign _037_[1] = input_valid_i ? (* src = "calculator.sv:82.29-82.42|calculator.sv:82.25-83.42" *) b_i[1] : 1'hx;
  assign _037_[2] = input_valid_i ? (* src = "calculator.sv:82.29-82.42|calculator.sv:82.25-83.42" *) b_i[2] : 1'hx;
  assign _037_[3] = input_valid_i ? (* src = "calculator.sv:82.29-82.42|calculator.sv:82.25-83.42" *) b_i[3] : 1'hx;
  assign _037_[4] = input_valid_i ? (* src = "calculator.sv:82.29-82.42|calculator.sv:82.25-83.42" *) b_i[4] : 1'hx;
  assign _038_[0] = _012_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _037_[0];
  assign _038_[1] = _012_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _037_[1];
  assign _038_[2] = _012_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _037_[2];
  assign _038_[3] = _012_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _037_[3];
  assign _038_[4] = _012_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _037_[4];
  assign _001_[0] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _038_[0];
  assign _001_[1] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _038_[1];
  assign _001_[2] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _038_[2];
  assign _001_[3] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _038_[3];
  assign _001_[4] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _038_[4];
  assign _039_[0] = input_valid_i ? (* src = "calculator.sv:78.29-78.42|calculator.sv:78.25-79.42" *) a_i[0] : 1'hx;
  assign _039_[1] = input_valid_i ? (* src = "calculator.sv:78.29-78.42|calculator.sv:78.25-79.42" *) a_i[1] : 1'hx;
  assign _039_[2] = input_valid_i ? (* src = "calculator.sv:78.29-78.42|calculator.sv:78.25-79.42" *) a_i[2] : 1'hx;
  assign _039_[3] = input_valid_i ? (* src = "calculator.sv:78.29-78.42|calculator.sv:78.25-79.42" *) a_i[3] : 1'hx;
  assign _039_[4] = input_valid_i ? (* src = "calculator.sv:78.29-78.42|calculator.sv:78.25-79.42" *) a_i[4] : 1'hx;
  assign _040_[0] = _011_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _039_[0];
  assign _040_[1] = _011_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _039_[1];
  assign _040_[2] = _011_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _039_[2];
  assign _040_[3] = _011_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _039_[3];
  assign _040_[4] = _011_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:76.17-89.24" *) 1'hx : _039_[4];
  assign _000_[0] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _040_[0];
  assign _000_[1] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _040_[1];
  assign _000_[2] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _040_[2];
  assign _000_[3] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _040_[3];
  assign _000_[4] = clear_i ? (* src = "calculator.sv:71.17-71.24|calculator.sv:71.13-90.16" *) 1'h0 : _040_[4];
  assign _041_[1] = ~(* src = "calculator.sv:53.21-53.27|calculator.sv:53.17-56.39" *) calc_i;
  assign _041_[2] = ~(* src = "calculator.sv:47.21-47.34|calculator.sv:47.17-50.41" *) input_valid_i;
  assign next_state[0] = _045_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:598.13-598.25" *) _044_[0] : 1'h0;
  assign next_state[1] = _045_ ? (* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:598.13-598.25" *) _044_[1] : 1'h0;
  assign \addsub_inst.FA_CHAIN[4].FA.sum_o  = _036_ ^(* src = "fulladder.sv:12.20-12.35" *)  \addsub_inst.FA_CHAIN[4].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[3].FA.sum_o  = _035_ ^(* src = "fulladder.sv:12.20-12.35" *)  \addsub_inst.FA_CHAIN[3].FA.c_i ;
  assign _031_ = reg_a[3] &(* src = "fulladder.sv:13.21-13.30" *)  \addsub_inst.FA_CHAIN[3].FA.b_i ;
  assign _032_ = \addsub_inst.FA_CHAIN[3].FA.b_i  &(* src = "fulladder.sv:13.35-13.44" *)  \addsub_inst.FA_CHAIN[3].FA.c_i ;
  assign _034_ = _031_ |(* src = "fulladder.sv:13.20-13.45" *)  _032_;
  assign _033_ = reg_a[3] &(* src = "fulladder.sv:13.49-13.58" *)  \addsub_inst.FA_CHAIN[3].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[4].FA.c_i  = _034_ |(* src = "fulladder.sv:13.20-13.59" *)  _033_;
  assign \addsub_inst.FA_CHAIN[2].FA.sum_o  = _030_ ^(* src = "fulladder.sv:12.20-12.35" *)  \addsub_inst.FA_CHAIN[2].FA.c_i ;
  assign _026_ = reg_a[2] &(* src = "fulladder.sv:13.21-13.30" *)  \addsub_inst.FA_CHAIN[2].FA.b_i ;
  assign _027_ = \addsub_inst.FA_CHAIN[2].FA.b_i  &(* src = "fulladder.sv:13.35-13.44" *)  \addsub_inst.FA_CHAIN[2].FA.c_i ;
  assign _029_ = _026_ |(* src = "fulladder.sv:13.20-13.45" *)  _027_;
  assign _028_ = reg_a[2] &(* src = "fulladder.sv:13.49-13.58" *)  \addsub_inst.FA_CHAIN[2].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[3].FA.c_i  = _029_ |(* src = "fulladder.sv:13.20-13.59" *)  _028_;
  assign \addsub_inst.FA_CHAIN[1].FA.sum_o  = _025_ ^(* src = "fulladder.sv:12.20-12.35" *)  \addsub_inst.FA_CHAIN[1].FA.c_i ;
  assign _021_ = reg_a[1] &(* src = "fulladder.sv:13.21-13.30" *)  \addsub_inst.FA_CHAIN[1].FA.b_i ;
  assign _022_ = \addsub_inst.FA_CHAIN[1].FA.b_i  &(* src = "fulladder.sv:13.35-13.44" *)  \addsub_inst.FA_CHAIN[1].FA.c_i ;
  assign _024_ = _021_ |(* src = "fulladder.sv:13.20-13.45" *)  _022_;
  assign _023_ = reg_a[1] &(* src = "fulladder.sv:13.49-13.58" *)  \addsub_inst.FA_CHAIN[1].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[2].FA.c_i  = _024_ |(* src = "fulladder.sv:13.20-13.59" *)  _023_;
  assign \addsub_inst.FA_CHAIN[0].FA.sum_o  = _020_ ^(* src = "fulladder.sv:12.20-12.35" *)  mode_i;
  assign _016_ = reg_a[0] &(* src = "fulladder.sv:13.21-13.30" *)  \addsub_inst.FA_CHAIN[0].FA.b_i ;
  assign _017_ = \addsub_inst.FA_CHAIN[0].FA.b_i  &(* src = "fulladder.sv:13.35-13.44" *)  mode_i;
  assign _019_ = _016_ |(* src = "fulladder.sv:13.20-13.45" *)  _017_;
  assign _018_ = reg_a[0] &(* src = "fulladder.sv:13.49-13.58" *)  mode_i;
  assign \addsub_inst.FA_CHAIN[1].FA.c_i  = _019_ |(* src = "fulladder.sv:13.20-13.59" *)  _018_;
  assign _036_ = reg_a[4] ^(* src = "fulladder.sv:12.20-12.29" *)  \addsub_inst.FA_CHAIN[4].FA.b_i ;
  assign _035_ = reg_a[3] ^(* src = "fulladder.sv:12.20-12.29" *)  \addsub_inst.FA_CHAIN[3].FA.b_i ;
  assign _030_ = reg_a[2] ^(* src = "fulladder.sv:12.20-12.29" *)  \addsub_inst.FA_CHAIN[2].FA.b_i ;
  assign _025_ = reg_a[1] ^(* src = "fulladder.sv:12.20-12.29" *)  \addsub_inst.FA_CHAIN[1].FA.b_i ;
  assign _020_ = reg_a[0] ^(* src = "fulladder.sv:12.20-12.29" *)  \addsub_inst.FA_CHAIN[0].FA.b_i ;
  assign \addsub_inst.FA_CHAIN[0].FA.b_i  = reg_b[0] ^(* src = "addsub.sv:16.20-16.37" *)  mode_i;
  assign \addsub_inst.FA_CHAIN[1].FA.b_i  = reg_b[1] ^(* src = "addsub.sv:16.20-16.37" *)  mode_i;
  assign \addsub_inst.FA_CHAIN[2].FA.b_i  = reg_b[2] ^(* src = "addsub.sv:16.20-16.37" *)  mode_i;
  assign \addsub_inst.FA_CHAIN[3].FA.b_i  = reg_b[3] ^(* src = "addsub.sv:16.20-16.37" *)  mode_i;
  assign \addsub_inst.FA_CHAIN[4].FA.b_i  = reg_b[4] ^(* src = "addsub.sv:16.20-16.37" *)  mode_i;
  assign _042_[4] = input_valid_i &(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:586.44-586.84" *)  _043_[2];
  assign _042_[2] = _041_[2] &(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:586.44-586.84" *)  _043_[1];
  assign _042_[3] = input_valid_i &(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:586.44-586.84" *)  _043_[1];
  assign _042_[1] = _041_[1] &(* src = "calculator.sv:0.0-0.0|calculator.sv:39.9-59.16|/opt/homebrew/bin/../share/yosys/techmap.v:586.44-586.84" *)  output_valid_o;
  assign { _041_[5:3], _041_[0] } = { 1'h0, input_valid_i, input_valid_i, 1'h0 };
  assign { _042_[5], _042_[0] } = 2'h0;
  assign _043_[0] = output_valid_o;
  assign \addsub_inst.FA_CHAIN[0].FA.a_i  = reg_a[0];
  assign \addsub_inst.FA_CHAIN[0].FA.c_i  = mode_i;
  assign \addsub_inst.FA_CHAIN[0].FA.c_o  = \addsub_inst.FA_CHAIN[1].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[1].FA.a_i  = reg_a[1];
  assign \addsub_inst.FA_CHAIN[1].FA.c_o  = \addsub_inst.FA_CHAIN[2].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[2].FA.a_i  = reg_a[2];
  assign \addsub_inst.FA_CHAIN[2].FA.c_o  = \addsub_inst.FA_CHAIN[3].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[3].FA.a_i  = reg_a[3];
  assign \addsub_inst.FA_CHAIN[3].FA.c_o  = \addsub_inst.FA_CHAIN[4].FA.c_i ;
  assign \addsub_inst.FA_CHAIN[4].FA.a_i  = reg_a[4];
  assign \addsub_inst.a_i  = reg_a;
  assign \addsub_inst.b_i  = reg_b;
  assign \addsub_inst.b_mux  = { \addsub_inst.FA_CHAIN[4].FA.b_i , \addsub_inst.FA_CHAIN[3].FA.b_i , \addsub_inst.FA_CHAIN[2].FA.b_i , \addsub_inst.FA_CHAIN[1].FA.b_i , \addsub_inst.FA_CHAIN[0].FA.b_i  };
  assign \addsub_inst.c [4:0] = { \addsub_inst.FA_CHAIN[4].FA.c_i , \addsub_inst.FA_CHAIN[3].FA.c_i , \addsub_inst.FA_CHAIN[2].FA.c_i , \addsub_inst.FA_CHAIN[1].FA.c_i , mode_i };
  assign \addsub_inst.mode_i  = mode_i;
  assign \addsub_inst.result_o  = { \addsub_inst.FA_CHAIN[4].FA.sum_o , \addsub_inst.FA_CHAIN[3].FA.sum_o , \addsub_inst.FA_CHAIN[2].FA.sum_o , \addsub_inst.FA_CHAIN[1].FA.sum_o , \addsub_inst.FA_CHAIN[0].FA.sum_o  };
  assign result_o = { \addsub_inst.FA_CHAIN[4].FA.sum_o , \addsub_inst.FA_CHAIN[3].FA.sum_o , \addsub_inst.FA_CHAIN[2].FA.sum_o , \addsub_inst.FA_CHAIN[1].FA.sum_o , \addsub_inst.FA_CHAIN[0].FA.sum_o  };
endmodule
