# Testcase Structure:
#    name: String, // The name of the testcase
#    subname: Option<String>, // used for unittests later
#    testcase_type: String, //Only IO supported now
#    description: Option<String>, // optional description
#    args: Option<String>, // command line arguments 
#    cflags: Option<String>, // compile flags
#    tags: Option<Tags>, // tags for unit tests
#    in_file: Option<String>, // stdin file 
#    exp_file: Option<String>, // stdout file
#    in_string: Option<String>, // stdin string (in_file has higher priority)
#    exp_string: Option<String>, // stdout string (out_file has higher priority)
#    exp_retvar: Option<i32>, // optional expected status code
#    timeout: Option<i32>, // timeout in seconds .. default is 5 sec
#    env_vars:Option<String>, // optional environment parameters RAND_SEED=123,foo=bar

[project_definition]
project_name = "main"
makefile_path = "."
maketarget = "all"

[[testcases]]
name = "Basic"
testcase_type = "IO"
in_file = "tests/01/in"
exp_file = "tests/01/out"
args = ["tests/01/cfg01.txt"]
exp_retvar = 0

[[testcases]]
name = "Basic 2.0"
testcase_type = "IO"
in_file = "tests/02/in"
exp_file = "tests/02/out"
args = ["tests/02/cfg02.txt"]
exp_retvar = 0

[[testcases]]
name = "Too many words"
testcase_type = "IO"
in_file = "tests/03/in"
exp_file = "tests/03/out"
args = ["tests/03/cfg03.txt"]
exp_retvar = 3

[[testcases]]
name = "Spaces"
testcase_type = "IO"
in_file = "tests/04/in"
exp_file = "tests/04/out"
args = ["tests/04/cfg04.txt"]
exp_retvar = 0

[[testcases]]
name = "Incorrect answers"
testcase_type = "IO"
in_file = "tests/05/in"
exp_file = "tests/05/out"
args = ["tests/05/cfg05.txt"]
exp_retvar = 0

[[testcases]]
name = "Missing words"
testcase_type = "IO"
in_file = "tests/06/in"
exp_file = "tests/06/out"
args = ["tests/06/cfg06.txt"]
exp_retvar = 3

[[testcases]]
name = "More missing words"
testcase_type = "IO"
in_file = "tests/07/in"
exp_file = "tests/07/out"
args = ["tests/07/cfg07.txt"]
exp_retvar = 3

[[testcases]]
name = "File cannot be opened"
testcase_type = "IO"
in_file = "tests/08/in"
exp_file = "tests/08/out"
args = ["tests/08/cfg08.txt"]
exp_retvar = 2

[[testcases]]
name = "No arguments"
testcase_type = "IO"
in_file = "tests/09/in"
exp_file = "tests/09/out"
exp_retvar = 1
