/* Generated by Yosys 0.46 (git sha1 e97731b9d, clang++ 16.0.0 -fPIC -O3) */

(* src = "simple_circuit.sv:1.1-8.10" *)
module simple_circuit(in_a, in_b, in_c, out_q);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "simple_circuit.sv:2.15-2.19" *)
  input in_a;
  wire in_a;
  (* src = "simple_circuit.sv:3.15-3.19" *)
  input in_b;
  wire in_b;
  (* src = "simple_circuit.sv:4.15-4.19" *)
  input in_c;
  wire in_c;
  (* src = "simple_circuit.sv:5.16-5.21" *)
  output out_q;
  wire out_q;
  NOT _3_ (
    .A(in_a),
    .Y(_0_)
  );
  NOT _4_ (
    .A(in_c),
    .Y(_1_)
  );
  NAND _5_ (
    .A(in_b),
    .B(_0_),
    .Y(_2_)
  );
  NAND _6_ (
    .A(_1_),
    .B(_2_),
    .Y(out_q)
  );
endmodule
